backend:
  name: github
  repo: giopunt/connects-cast

media_folder: static/assets
public_folder: /assets

collections:
  - name: insight
    label: Insight
    folder: insights
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: excerpt, label: Excerpt, widget: string }
      - { name: content, label: Content, widget: markdown }